/* 
 * This code file is generated by ApService Proxy Generator tool.
 * Service Name    : MailServer
 * Service version : 1.0.0.0
 * Generating date : 2015-06-28 11:32:20
 */

using ApCommLib;

using System;
using System.Data;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace Stomp.Proxy
{
    /// <summary>
    /// This class is a proxy class to use MailServer service.
    /// Description: 邮件服务
    /// </summary>
    public partial class MailServerProxy : ApServiceProxyBase
    {
        #region Constructor
        
        /// <summary>
        ///  Creates a new instance of MailServerProxy.
        /// </summary>
        /// <param name="serviceConsumerName">Reference to a ApServiceConsumer object to send/receive messages</param>
        public MailServerProxy(string serviceConsumerName = "Activemq.Server")
            : base("MailServer",serviceConsumerName)
        {
            
        }
        
        #endregion
        
        #region MailServer methods
        
        /// <summary>
        /// 发送邮件
        /// </summary>
        /// <param name="touser">收件人</param>
        public void SendMial(string touser)
        {
            InvokeMethod("SendMial", touser);
        }
        
        #endregion
        
        #region Default (predefined) service methods
        
        /// <summary>
        /// This method can be used to check if service is available.
        /// </summary>
        /// <param name="message">A message to reply</param>
        /// <returns>Reply to message as formatted: 'RE: message'</returns>
        public string CheckServiceIsAvailable(string message)
        {
            return (string) InvokeMethodAndResult("CheckServiceIsAvailable", message);
        }
        
        #endregion
    }
}

